PengRaSi/PengRaSi/PengRaSi/Controllers/AnnounceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    public class AnnounceController : Controller
    {
        private pengrasiEntities db = new pengrasiEntities();

        // GET: Announce
        public ActionResult Index()
        {
            return View(db.TBL_ANNOUNCE.ToList());
        }

        // GET: Announce/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_ANNOUNCE tBL_ANNOUNCE = db.TBL_ANNOUNCE.Find(id);
            if (tBL_ANNOUNCE == null)
            {
                return HttpNotFound();
            }
            return View(tBL_ANNOUNCE);
        }

        // GET: Announce/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Announce/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_ANNOUNCE,ANNOUNCEMENT")] TBL_ANNOUNCE tBL_ANNOUNCE)
        {
            if (ModelState.IsValid)
            {
                db.TBL_ANNOUNCE.Add(tBL_ANNOUNCE);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tBL_ANNOUNCE);
        }

        // GET: Announce/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_ANNOUNCE tBL_ANNOUNCE = db.TBL_ANNOUNCE.Find(id);
            if (tBL_ANNOUNCE == null)
            {
                return HttpNotFound();
            }
            return View(tBL_ANNOUNCE);
        }

        // POST: Announce/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_ANNOUNCE,ANNOUNCEMENT")] TBL_ANNOUNCE tBL_ANNOUNCE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tBL_ANNOUNCE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tBL_ANNOUNCE);
        }

        // GET: Announce/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_ANNOUNCE tBL_ANNOUNCE = db.TBL_ANNOUNCE.Find(id);
            if (tBL_ANNOUNCE == null)
            {
                return HttpNotFound();
            }
            return View(tBL_ANNOUNCE);
        }

        // POST: Announce/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TBL_ANNOUNCE tBL_ANNOUNCE = db.TBL_ANNOUNCE.Find(id);
            db.TBL_ANNOUNCE.Remove(tBL_ANNOUNCE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PengRaSi/PengRaSi/PengRaSi/Views/Announce/Create.cshtml
@model PengRaSi.TBL_ANNOUNCE



@{
    ViewBag.Title = "Create";
}
<h1 class="mt-4"></h1>
<h2>Announcement / Reminder</h2>
<ol class="breadcrumb mb-4">
    @Html.Partial("~/Views/Shared/_PartialCrumb.cshtml")
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Announce")">Announcement / Reminder</a></li>
    <li class="breadcrumb-item active">Add</li>
</ol>
<span class="text-danger">@ViewData["data"]</span>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <font class="text-danger" size="5">*</font>@Html.Label("Message", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ANNOUNCEMENT, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.ANNOUNCEMENT, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <font class="text-danger" size="2">Note : * Must Be Filled</font>
            </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
}






@*@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TBL_ANNOUNCE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ANNOUNCEMENT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ANNOUNCEMENT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ANNOUNCEMENT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

PengRaSi/PengRaSi/PengRaSi/Views/Announce/Delete.cshtml
@model PengRaSi.TBL_ANNOUNCE


@{
    ViewBag.Title = "Delete";
}
<h1 class="mt-4"></h1>
<h2>Announcement / Reminder</h2>
<ol class="breadcrumb mb-4">
    @Html.Partial("~/Views/Shared/_PartialCrumb.cshtml")
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Announce")">Announcement / Reminder</a></li>
    <li class="breadcrumb-item active">Delete</li>
</ol>
<span class="text-danger">@ViewData["data"]</span>
<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <table class="table" style="border-collapse :collapse" ; border:none">
        <tr>
            <td><li><b>Message :</b> @Html.DisplayFor(model => model.ANNOUNCEMENT)</li> </td>

        </tr>

    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>









@*@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TBL_ANNOUNCE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ANNOUNCEMENT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ANNOUNCEMENT)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

PengRaSi/PengRaSi/PengRaSi/Views/Announce/Details.cshtml
@model PengRaSi.TBL_ANNOUNCE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TBL_ANNOUNCE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ANNOUNCEMENT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ANNOUNCEMENT)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_ANNOUNCE }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PengRaSi/PengRaSi/PengRaSi/Views/Announce/Edit.cshtml
@model PengRaSi.TBL_ANNOUNCE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TBL_ANNOUNCE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_ANNOUNCE)

        <div class="form-group">
            @Html.LabelFor(model => model.ANNOUNCEMENT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ANNOUNCEMENT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ANNOUNCEMENT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PengRaSi/PengRaSi/PengRaSi/Views/Announce/Index.cshtml
@model IEnumerable<PengRaSi.TBL_ANNOUNCE>

@{
    ViewBag.Title = "Index";
}
<h1 class="mt-4"></h1>
<h2>Announcement / Reminder</h2>
<ol class="breadcrumb mb-4">
    @Html.Partial("~/Views/Shared/_PartialCrumb.cshtml")
    <li class="breadcrumb-item active">Announce</li>
</ol>
<span class="text-danger">@ViewData["data"]</span>
<p>
    @Html.ActionLink("Add New Announce/Remender", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>

<div class="card mb-4">
    <div class="card-header"><i class="fas fa-table mr-1"></i>Grade Data</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th> Message</th>
                        <th> Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th> Message</th>
                        <th> Action</th>
                    </tr>
                </tfoot>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ANNOUNCEMENT)
                        </td>
                        <td>
                            @*@Html.ActionLink("Edit", "Edit", new { id = item.ID_GRADE }, htmlAttributes: new { @class = "btn btn-primary" }) |*@
                            @*@Html.ActionLink("Details", "Details", new { id = item.ID_GRADE }, htmlAttributes: new { @class = "btn btn-success" }) |*@
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID_ANNOUNCE }, htmlAttributes: new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>