PengRaSi/PengRaSi/PengRaSi/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    [Authorize]
    [Authorize(Roles = "Administrator")]
    public class ProvinceController : Controller
    {
        private pengrasiEntities db = new pengrasiEntities();

        // GET: Province
        public ActionResult Index()
        {
            return View(db.MS_PROV.ToList());
        }

       

        // GET: Province/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Province/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PROV,PROVINCE")] MS_PROV mS_PROV)
        {
            if (ModelState.IsValid)
            {
                db.MS_PROV.Add(mS_PROV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mS_PROV);
        }

        

        // GET: Province/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MS_PROV mS_PROV = db.MS_PROV.Find(id);
            db.MS_PROV.Remove(mS_PROV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PengRaSi/PengRaSi/PengRaSi/Views/Province/Create.cshtml
@model PengRaSi.MS_PROV

@{
    ViewBag.Title = "Create";
}

<h1 class="mt-4"></h1>
<h2>Add Province </h2>
<ol class="breadcrumb mb-4">
    @Html.Partial("~/Views/Shared/_PartialCrumb.cshtml")
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Province")">Master Province</a></li>
    <li class="breadcrumb-item active">Add Province</li>
</ol>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Province", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PROVINCE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PROVINCE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PengRaSi/PengRaSi/PengRaSi/Views/Province/Index.cshtml
@model IEnumerable<PengRaSi.MS_PROV>

@{
    ViewBag.Title = "Index";
}

<h1 class="mt-4"></h1>
<span class="text-danger">@ViewData["data"]</span>
<h2>Master Province</h2>
<ol class="breadcrumb mb-4">
    @Html.Partial("~/Views/Shared/_PartialCrumb.cshtml")
    <li class="breadcrumb-item active">Master Province</li>
</ol>
<p>
    @Html.ActionLink("Add New Province", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
</p>

<div class="card mb-4">
    <div class="card-header"><i class="fas fa-table mr-1"></i>Province Data</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Province</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Province</th>
                        <th>Action</th>
                    </tr>
                </tfoot>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.PROVINCE)
                        </td>
                        <td>
                            @{
                                pengrasiEntities db = new pengrasiEntities();

                                var getFkidsubject = db.MS_CITY.Where(x => x.FK_ID_PROVENCE == item.ID_PROV);

                                if (!getFkidsubject.Any())
                                {
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID_PROV }, htmlAttributes: new { @class = "btn btn-danger", @onclick = "return confirm('Are you sure want to delete this data?');" })
                                }
                            }


                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>