PengRaSi/PengRaSi/PengRaSi/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    [Authorize]
    [Authorize(Roles = "Administrator")]
    public class CityController : Controller
    {
        private pengrasiEntities db = new pengrasiEntities();

        // GET: City
        public ActionResult Index()
        {
            var mS_CITY = db.MS_CITY.Include(m => m.MS_PROV);
            return View(mS_CITY.ToList());
        }

        

        // GET: City/Create
        public ActionResult Create()
        {
            ViewBag.FK_ID_PROVENCE = new SelectList(db.MS_PROV, "ID_PROV", "PROVINCE");
            return View();
        }

        // POST: City/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_CITY,CITY,FK_ID_PROVENCE")] MS_CITY mS_CITY)
        {
            if (ModelState.IsValid)
            {
                db.MS_CITY.Add(mS_CITY);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_ID_PROVENCE = new SelectList(db.MS_PROV, "ID_PROV", "PROVINCE", mS_CITY.FK_ID_PROVENCE);
            return View(mS_CITY);
        }

        

        // GET: City/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MS_CITY mS_CITY = db.MS_CITY.Find(id);
            db.MS_CITY.Remove(mS_CITY);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PengRaSi/PengRaSi/PengRaSi/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PengRaSi.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class SchoolController : Controller
    {
        pengrasiEntities db = new pengrasiEntities();
        // GET: School
        public ActionResult Index()
        {
            return RedirectToAction("Index","Home");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include ="SCHOOL_NAME, SCHOOL_ADDRESS")] MS_SCHOOL mS_SCHOOL, HttpPostedFileBase postedFile)
        {
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }

            mS_SCHOOL.SCHOOL_LOGO = bytes;

            if(ModelState.IsValid)
            {
                db.MS_SCHOOL.Add(mS_SCHOOL);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View(mS_SCHOOL);
        }



        public ActionResult Edit()
        {

            var tb_Sch = db.MS_SCHOOL.FirstOrDefault();

            if (tb_Sch == null)
            {
                return RedirectToAction("Create");
            }
            
            return View(tb_Sch);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include ="ID_SCHOOL, SCHOOL_NAME, SCHOOL_ADDRESS, SCHOOL_LOGO")] MS_SCHOOL mS_SCHOOL, HttpPostedFileBase postedFile)
        {
            byte[] bytes;
            if (postedFile!=null)
            {
                using (BinaryReader br = new BinaryReader(postedFile.InputStream))
                {
                    bytes = br.ReadBytes(postedFile.ContentLength);
                }
                mS_SCHOOL.SCHOOL_LOGO = bytes;
            }
            

            if(ModelState.IsValid)
            {
                db.Entry(mS_SCHOOL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(mS_SCHOOL);
        }
    }

    
}

PengRaSi/PengRaSi/PengRaSi/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PengRaSi.Controllers
{
    public class TestController : Controller
    {
        pengrasiEntities db = new pengrasiEntities();
        // GET: Test
        [Authorize(Roles = "Teacher,Homeroom Teacher,Administrator")]
        public ActionResult Teacher()
        {
            var tbUser = db.TBL_USER.Where(x => x.ID_USER == User.Identity.Name).FirstOrDefault();
            var tbTeacher = db.TBL_TEACHER.Where(x => x.ID_TEACHER == tbUser.FK_ID_TEACHER).FirstOrDefault();
            var tbSubj = db.TBL_SUBJECT_CLASS.Where(x => x.FK_ID_TEACHER == tbTeacher.ID_TEACHER);
           
            ViewBag.Teacher = tbTeacher;
            ViewData["Subject"] = tbSubj;
            ViewBag.ListSubject = tbSubj.AsEnumerable().GroupBy(x => x.FK_ID_SUBJECT).Select(x => x.First());
            return View(tbSubj);
        }
        [Authorize(Roles = "Homeroom Teacher,Administrator")]
        public ActionResult HomeroomTeacher()
        {
          
            var Notifdt = DateTime.Now.ToString("dd/MM/yyyy hh:mm:ss");

            ViewData["time"] = Notifdt;
            return View();
        }
    }
}

PengRaSi/PengRaSi/PengRaSi/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UserController : Controller
    {
        private pengrasiEntities db = new pengrasiEntities();

        Models.Encryption code = new Models.Encryption();
        

        // GET: User
        public ActionResult Index()
        {
            var tBL_USER = db.TBL_USER.Include(t => t.MS_ROLE).Include(t => t.TBL_TEACHER);
            return View(tBL_USER.ToList());
        }

        // GET: User/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_USER tBL_USER = db.TBL_USER.Find(id);
            if (tBL_USER == null)
            {
                return HttpNotFound();
            }
            return View(tBL_USER);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            ViewBag.POSITION = new SelectList(db.MS_ROLE, "ROLE", "ROLE");
            ViewBag.FK_ID_TEACHER = new SelectList(db.TBL_TEACHER, "ID_TEACHER", "TEACHER_NAME");
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_USER,PASSWORD,POSITION,FK_ID_TEACHER")] TBL_USER tBL_USER)
        {
            string a = tBL_USER.FK_ID_TEACHER;
            string b = tBL_USER.ID_USER;

            //TBL_TEACHER tBL_TEACHERnew = new TBL_TEACHER();

            TBL_USER tb_user = db.TBL_USER.Where(x => x.FK_ID_TEACHER == a).FirstOrDefault();
            TBL_USER tb_user1 = db.TBL_USER.Where(x => x.ID_USER == b).FirstOrDefault();
            TBL_TEACHER tb_teacher = db.TBL_TEACHER.Where(x => x.ID_TEACHER == a).FirstOrDefault();
            TBL_HOMEROOM tb_homeroom = db.TBL_HOMEROOM.Where(x => x.FK_ID_TEACHER == tb_teacher.ID_TEACHER).FirstOrDefault();


            TBL_USER tb_userNOTIF = db.TBL_USER.Where(x => x.ID_USER == @User.Identity.Name).FirstOrDefault();
            TBL_TEACHER tb_teacherNOTIF = db.TBL_TEACHER.Where(x => x.ID_TEACHER == tb_userNOTIF.FK_ID_TEACHER).FirstOrDefault();

            if (tBL_USER.POSITION == "Homeroom Teacher")
            {
                if (tb_user1 == null)
                {
                    if (tb_user == null)
                    {
                        if (tb_homeroom != null)
                        {
                            using (DbContextTransaction ts = db.Database.BeginTransaction())
                            {
                                try
                                {
                                    String encrypted = code.Encrypt(tBL_USER.PASSWORD);
                                    tBL_USER.PASSWORD = encrypted;
                                    db.TBL_USER.Add(tBL_USER);
                                    //db.SaveChanges();
                                    int valuenotif1 = 0;
                                    if (valuenotif1 == 0)
                                    {
                                        TBL_NOTIF tBL_NOTIF = new TBL_NOTIF();
                                        tBL_NOTIF.INBOX = "Please Changes Your Password";
                                        tBL_NOTIF.FK_ID_USER_RECEIVER = tBL_USER.ID_USER;
                                        tBL_NOTIF.SENDER = tb_teacherNOTIF.TEACHER_NAME;
                                        tBL_NOTIF.DATE_NOTIF = DateTime.Now;
                                        db.TBL_NOTIF.Add(tBL_NOTIF);

                                        TBL_TRACKNOTIF tBL_TRACKNOTIF = new TBL_TRACKNOTIF();
                                        tBL_TRACKNOTIF.INBOX = tBL_NOTIF.INBOX;
                                        tBL_TRACKNOTIF.FK_ID_USER_RECEIVER = tBL_NOTIF.FK_ID_USER_RECEIVER;
                                        tBL_TRACKNOTIF.SENDER = tBL_NOTIF.SENDER;
                                        tBL_TRACKNOTIF.DATE_NOTIF = tBL_NOTIF.DATE_NOTIF;
                                        tBL_TRACKNOTIF.DATE_ACTION = DateTime.Now;
                                        TBL_USER tb_userNOTIF1 = db.TBL_USER.Where(x => x.ID_USER == @User.Identity.Name).FirstOrDefault();
                                        TBL_TEACHER tb_teacherNOTIF1 = db.TBL_TEACHER.Where(x => x.ID_TEACHER == tb_userNOTIF.FK_ID_TEACHER).FirstOrDefault();
                                        tBL_TRACKNOTIF.ACTION_NOTIF = "[CREATE USER] By " + tb_teacherNOTIF1.TEACHER_NAME;
                                        db.TBL_TRACKNOTIF.Add(tBL_TRACKNOTIF);

                                        db.SaveChanges();
                                        ts.Commit();
                                    }
                                    return RedirectToAction("Index");

                                }
                                catch (Exception)
                                {
                                    ts.Rollback();
                                    ViewData["data"] = "Something Error Or Username Same";
                                }
                            }

                        }
                        else
                        {
                            ViewData["homeroom"] = "Please First Add A Teacher Who Wants To Be Homeroom Teacher At Menu Manage Homeroom Teacher";
                        }

                    }
                    else
                    {
                        ViewData["sama"] = "User Already or Username Same..!!";
                    }

                }
                else
                {
                    ViewData["sama"] = "User Already or Username Same..!!";
                }
            }
            else
            {
                if (tb_user == null)
                {
                    using (DbContextTransaction ts = db.Database.BeginTransaction())
                    {
                        try
                        {
                            String encrypted = code.Encrypt(tBL_USER.PASSWORD);
                            tBL_USER.PASSWORD = encrypted;
                            db.TBL_USER.Add(tBL_USER);
                            //db.SaveChanges();
                            int valuenotif1 = 0;
                            if (valuenotif1 == 0)
                            {
                                TBL_NOTIF tBL_NOTIF = new TBL_NOTIF();
                                tBL_NOTIF.INBOX = "Please Changes Your Password";
                                tBL_NOTIF.FK_ID_USER_RECEIVER = tBL_USER.ID_USER;
                                tBL_NOTIF.SENDER = tb_teacherNOTIF.TEACHER_NAME;
                                tBL_NOTIF.DATE_NOTIF = DateTime.Now;
                                db.TBL_NOTIF.Add(tBL_NOTIF);

                                TBL_TRACKNOTIF tBL_TRACKNOTIF = new TBL_TRACKNOTIF();
                                tBL_TRACKNOTIF.INBOX = tBL_NOTIF.INBOX;
                                tBL_TRACKNOTIF.FK_ID_USER_RECEIVER = tBL_NOTIF.FK_ID_USER_RECEIVER;
                                tBL_TRACKNOTIF.SENDER = tBL_NOTIF.SENDER;
                                tBL_TRACKNOTIF.DATE_NOTIF = tBL_NOTIF.DATE_NOTIF;
                                tBL_TRACKNOTIF.DATE_ACTION = DateTime.Now;
                                TBL_USER tb_userNOTIF1 = db.TBL_USER.Where(x => x.ID_USER == @User.Identity.Name).FirstOrDefault();
                                TBL_TEACHER tb_teacherNOTIF1 = db.TBL_TEACHER.Where(x => x.ID_TEACHER == tb_userNOTIF.FK_ID_TEACHER).FirstOrDefault();
                                tBL_TRACKNOTIF.ACTION_NOTIF = "[CREATE USER] By " + tb_teacherNOTIF1.TEACHER_NAME;
                                db.TBL_TRACKNOTIF.Add(tBL_TRACKNOTIF);
                                db.SaveChanges();
                                ts.Commit();
                            }

                            return RedirectToAction("Index");

                        }
                        catch (Exception)
                        {
                            ts.Rollback();
                            ViewData["data"] = "Something Error Or Username Same";
                        }
                    }
                }
                else
                {
                    ViewData["sama"] = "User Already or Username Same..!!";
                }
                   
            }


            ViewBag.POSITION = new SelectList(db.MS_ROLE, "ROLE", "ROLE", tBL_USER.POSITION);
            ViewBag.FK_ID_TEACHER = new SelectList(db.TBL_TEACHER, "ID_TEACHER", "TEACHER_NAME", tBL_USER.FK_ID_TEACHER);
            return View(tBL_USER);
        }

        // GET: User/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_USER tBL_USER = db.TBL_USER.Find(id);
            if (tBL_USER == null)
            {
                return HttpNotFound();
            }
            ViewBag.POSITION = new SelectList(db.MS_ROLE, "ROLE", "ROLE", tBL_USER.POSITION);
            ViewBag.FK_ID_TEACHER = new SelectList(db.TBL_TEACHER, "ID_TEACHER", "TEACHER_NAME", tBL_USER.FK_ID_TEACHER);
            return View(tBL_USER);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

PengRaSi/PengRaSi/PengRaSi/Views/Shared/_PartialCrumb.cshtml
@{
    pengrasiEntities db = new pengrasiEntities();
    TBL_USER tbUser = db.TBL_USER.Where(x => x.ID_USER == User.Identity.Name).FirstOrDefault();
    var pos = tbUser.POSITION;

    if (pos == "Administrator")
    {
        <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Dashboard</a></li>
    }
    else if (pos == "Homeroom Teacher")
    {
        <li class="breadcrumb-item"><a href="@Url.Action("HomeroomTeacher","Test")">Dashboard</a></li>
    }
    else if (pos == "Teacher")
    {
        <li class="breadcrumb-item"><a href="@Url.Action("Teacher","Test")">Dashboard</a></li>
    }
}

PengRaSi/PengRaSi/PengRaSi/Views/Shared/_PartialSide.cshtml
@{
    /**/

    pengrasiEntities dbnav = new pengrasiEntities();
    TBL_USER tb_user = dbnav.TBL_USER.Where(x => x.ID_USER == @User.Identity.Name).FirstOrDefault();


}
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>

                @{if (@tb_user.POSITION == "Administrator")
                    {
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Master
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Edit", "School")">School Data</a>
                                <a class="nav-link" href="@Url.Action("Index", "Gender")">Gender</a>
                                <a class="nav-link" href="@Url.Action("Index", "Grade")">Grade</a>
                                <a class="nav-link" href="@Url.Action("Index", "Religion")">Religion</a>
                                <a class="nav-link" href="@Url.Action("Index", "Subject")">Subject</a>
                                <a class="nav-link" href="@Url.Action("Index", "Province")">Province</a>
                                <a class="nav-link" href="@Url.Action("Index", "City")">City</a>
                                <a class="nav-link" href="@Url.Action("Index", "Student")">Student</a>


                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsAdmin" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Admin
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayoutsAdmin" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index", "Department")">Manage Department</a>
                                <a class="nav-link" href="@Url.Action("Index", "Class")">Manage Class</a>
                                <a class="nav-link" href="@Url.Action("Index", "Teacher")">Manage Teacher</a>
                                <a class="nav-link" href="@Url.Action("Index", "HomeroomTeacher")">Manage Homeroom Teacher</a>
                                <a class="nav-link" href="@Url.Action("Index", "ClassSubject")">Class Subjects</a>
                                <a class="nav-link" href="@Url.Action("Index", "User")">Manage User</a>
                            </nav>
                        </div>
                        @*<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsHomeroomTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Homeroom Teacher
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayoutsHomeroomTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="#)">Manage Student</a>
                        <a class="nav-link" href="#">Manage Raport Student</a>
                    </nav>
                </div>*@
                        @*<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Teacher
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayoutsTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("IndexTeach", "ClassSubject")">Manage Score Student</a>
                            </nav>
                        </div>*@
                        <a class="nav-link" href="@Url.Action("Index", "Announce")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Announcement / Reminder
                        </a>
                    }

                }
                @{if (@tb_user.POSITION == "Homeroom Teacher")
                    {
                        <a class="nav-link" href="@Url.Action("HomeroomTeacher", "Test")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutshomeroomTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Homeroom Teacher
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayoutshomeroomTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("IndexHT", "Student")">Manage Student</a>
                                <a class="nav-link" href="@Url.Action("Index", "SubjectHomeroom")">Manage Score Student And Subject</a>
                                <a class="nav-link" href="@Url.Action("Index", "ClassAttendance")">Class Attendance</a>
                                <a class="nav-link" href="@Url.Action("SMTSel", "Student")">Student Ranking</a>
                                <a class="nav-link" href="@Url.Action("SMTSel", "NoteHomeroom")">Homeroom Note</a>
                                <a class="nav-link" href="@Url.Action("SMTSel", "StudentReport")">Student Report</a>

                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Teacher
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayoutsTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("IndexTeach", "ClassSubject")">Manage Score Student</a>
                                <a class="nav-link" href="@Url.Action("Edit", "Signature")">Signature</a>
                            </nav>
                        </div>

                    }
                }

                @{if (@tb_user.POSITION == "Teacher")
                    {
                        <a class="nav-link" href="@Url.Action("Teacher", "Test")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Teacher
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayoutsTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("IndexTeach", "ClassSubject")">Manage Score Student</a>
                                <a class="nav-link" href="@Url.Action("Edit", "Signature")">Signature</a>
                            </nav>
                        </div>

                    }
                }
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsNotif" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Notification
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayoutsNotif" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("Index", "Notification")">Inbox</a>
                    </nav>
                </div>
                <div class="collapse" id="collapseLayoutsNotif" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="@Url.Action("SentItem", "Notification")">Sent Item</a>
                    </nav>
                </div>
                @{if (@tb_user.POSITION == "Administrator")
                    {
                        <div class="collapse" id="collapseLayoutsNotif" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index", "TrackNotif")">History/Track Notif</a>
                            </nav>
                        </div>
                    }
                }
                @{if (@tb_user.POSITION == "Homeroom Teacher" || @tb_user.POSITION == "Teacher")
                    {
                        <div class="collapse" id="collapseLayoutsNotif" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("IndexTeach", "TrackNotif")">History/Track Notif</a>
                            </nav>
                        </div>
                    }
                }
                <!--
    <a class="nav-link" href="@Url.Action("Index","Notification")">
        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
        Notification
    </a>
    -->

            </div>
        </div>
        <div class="sb-sidenav-footer" style="background-color:#8ec3f6">
            <div class="small">Dev By:</div>
            Team 2  Didit & Pram
        </div>
    </nav>
</div>