Project(PengRaSi)/Bahan/PengRaSi/PengRaSi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    public class HomeController : Controller
    {
       

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

       


    }
}

Project(PengRaSi)/Bahan/PengRaSi/PengRaSi/Controllers/kelasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PengRaSi;

namespace PengRaSi.Controllers
{
    public class kelasController : Controller
    {
        private pengrasiEntitiesKelas db = new pengrasiEntitiesKelas();

        // GET: kelas
        public ActionResult Index()
        {
            return View(db.kelas.ToList());
        }

        // GET: kelas/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            kelas kelas = db.kelas.Find(id);
            if (kelas == null)
            {
                return HttpNotFound();
            }
            return View(kelas);
        }

        // GET: kelas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: kelas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_kelas,kelas1,jurusan")] kelas kelas)
        {
            if (ModelState.IsValid)
            {
                db.kelas.Add(kelas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kelas);
        }

        // GET: kelas/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            kelas kelas = db.kelas.Find(id);
            if (kelas == null)
            {
                return HttpNotFound();
            }
            return View(kelas);
        }

        // POST: kelas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_kelas,kelas1,jurusan")] kelas kelas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kelas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kelas);
        }

        // GET: kelas/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            kelas kelas = db.kelas.Find(id);
            if (kelas == null)
            {
                return HttpNotFound();
            }
            return View(kelas);
        }

        // POST: kelas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            kelas kelas = db.kelas.Find(id);
            db.kelas.Remove(kelas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project(PengRaSi)/Bahan/PengRaSi/PengRaSi/Views/Shared/Nav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="index"><h6>SMKN 8 KAB.TANGERANG</h6></a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button><!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="">Logout</a>
            </div>
        </li>
    </ul>
</nav>

Project(PengRaSi)/Bahan/PengRaSi/PengRaSi/Views/Shared/SideNav.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>

                <div class="sb-sidenav-menu-heading">Interface</div>

                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Admin
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="#">Manage Teacher</a><a class="nav-link" href="#">Manage Homeroom Teacher</a><a class="nav-link" href="@Url.Action("Index","kelas")">Manage Class</a><a class="nav-link" href="#">Manage Jurusan</a></nav>
                </div>



                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsHomelessTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Homeroom Teacher
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayoutsHomelessTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="#">Manage Student</a><a class="nav-link" href="#">Manage Raport Student</a></nav>
                </div>


                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayoutsTeacher" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Teacher
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayoutsTeacher" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="#">Manage Score Student</a></nav>
                </div>

            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Dev By:</div>
            Team 2  Didit & Pram
        </div>
    </nav>
</div>

Project(PengRaSi)/Bahan/PengRaSi/PengRaSi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>SMKN 8 KAB. TANGERANG</title>
    @Styles.Render("~/Content/css")

    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>